export const FETCH_ALL_PRODUCTS = 'FETCH_ALL_PRODUCTS';

export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';

export const CHANGE_CATEGORY_ID = 'CHANGE_CATEGORY_ID';

export const START_LOADING = 'START_LOADING';

export const END_LOADING = 'END_LOADING';